#!/bin/sh
# Copy early display binary and dependencies

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Copy our binary
copy_exec /usr/local/bin/early_display /bin/early_display

# Copy I2C modules and dependencies
manual_add_modules i2c-dev
manual_add_modules i2c-bcm2835

# Copy device node
mkdir -p ${DESTDIR}/dev/i2c-1
mknod ${DESTDIR}/dev/i2c-1 c 89 1
