#!/bin/sh
# Copy early display binary and dependencies

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Copy our binary
copy_exec /usr/local/bin/early_display /bin/early_display

# Ensure we have I2C modules
manual_add_modules i2c_dev
manual_add_modules i2c_bcm2835

# Copy any additional required libraries
copy_exec /lib/arm-linux-gnueabihf/libc.so.6
copy_exec /lib/arm-linux-gnueabihf/ld-linux-armhf.so.3
